### PR TITLE
Fix eudev post-install stage failure

### PR DESCRIPTION
**Pull request by charlesthobe**
plus changes from this: https://github.com/flathub/org.winehq.Wine/pull/73

### CODE REVIEW

**Comment by charlesthobe** [comment]
Okay this still fails, apologies

**Comment by charlesthobe** [comment]
~~works on my machine though, while without it, it doesn't work~~ :thinking:
nope it doesn't work on my machine currently.

**Comment by charlesthobe** [comment]
Funny because it worked the first time, I deleted all the sdk extensions, and deleted all the lines below eudev submodule and added the change, and it generated `/etc/udev/hwdb.bin` and just exited with couldn't find the command "wine", because I deleted the rest, but now absolutely nothing works on my machine, flatpak can be so frustrating.

**Comment by charlesthobe** [comment]
> Funny because it worked the first time, I deleted all the sdk extensions, and deleted all the lines below eudev submodule and added the change, and it generated `/etc/udev/hwdb.bin` and just exited with couldn't find the command "wine", because I deleted the rest, but now absolutely nothing works on my machine, flatpak can be so frustrating.

oh my guess is it was because I changed it on the stable branch, so the problematic version of eudev wasn't there.

**Comment by gasinvein** [comment]
Thanks!

**Comment by charlesthobe** [comment]
yw :smile:

**Comment by charlesthobe** [comment]
@gasinvein also I think this is worth checking out:
https://github.com/flathub/com.valvesoftware.Steam/blob/beta/modules.yml#L27
([permalink](https://github.com/flathub/com.valvesoftware.Steam/blob/5206bc6ea274faf94903442421764eaa656e8c3f/modules.yml#L27))
it installs `hwdb.bin` in `/app/lib/udev/hwdb.bin` instead of `/app/etc/udev/hwdb.bin`
just in case one is effective and the other is not, this PR installs in the latter which was the original behavior before the builds started to break.

**Comment by gasinvein** [comment]
Yeah, the fix applied for Steam was more correct. I've rushed merging this, sorry.

**Comment by charlesthobe** [comment]
no worries, you can do this one :+1:

**Pull request merged**
