### PR TITLE
Add Samba

### LINKED ISSUE #3: Include samba winbind runtime with the Flatpak
Microsoft Office 2010 and many other applications require samba winbind package to work properly. The current flatpak does not have this dependency included. It would be better if you offer this as a runtime dependency.

### PR DESCRIPTION
**Pull request by gasinvein**
Fixes #3

### CODE REVIEW

**Comment by Erick555** [comment]
I think 32bit samba won't be needed. There is no such thing in Arch and it works there with just 64bit samba (for 32bit windows app).

**Comment by gasinvein** [comment]
bot, build

**Comment by gasinvein** [comment]
@mirkobrombin You can remove Samba and its direct dependencies from the Bottles flatpak bundle since this PR landed.

**Comment by mirkobrombin** [comment]
Thanks

**Pull request merged**
